const path = {
  PUBLIC: '/',
  HOME: '/',
  LOGIN: 'login',
  MY_MUSIC: 'khampha',
  ZING_CHART: 'zing-chart',
  PLAYLIST__TITLE_PID: 'playlist/:title/:pid',
  CHILL__TITLE_PID: 'album/:title/:pid',
  WEEKCHART_TITLE_PID: 'zing-chart-tuan/:title/:pid',
  RADIO_TITLE_PID: 'radio/:title/:pid',
  RADIO: 'radio',
  SEARCH: 'tim-kiem',
  SEARCH_ALL: 'tat-ca',
  SEARCH_SONGS: 'bai-hat',
  SEARCH_PLAYLIST: 'playlist',
  SINGER__NAME: ':name',
  NEW_RELEASE_CHART: 'moi-phat-hanh',
  HUB_MUSIC: 'hub',
  TOP_100: 'top100',
  HISTORY_MUSIC: 'mymusic/history',
  LIKE_MUSIC: 'bai-hat-yeu-thich',
  PLAYLIST_MUSIC: 'playlist',
  ALBUM_MUSIC: 'album',
  LIBRARY_MUSIC: 'thuvien',
};

export default path;
