const actionTypers = {
  GET_HOME: 'GET_HOME',
  GET_SONG: 'GET_SONG',
  GET_MUSIC: 'GET_MUSIC',
  PLAY: 'PLAY',
  LOADING: 'LOADING',
  PLAYLIST: 'PLAYLIST',
  RECENT_SONG: 'RECENT_SONG',
  SEARCH: 'SEARCH',
  SEARCH_SONG: 'SEARCH_SONG',
  COUNTRY: 'COUNTRY',
};

export default actionTypers;
